### ISSUE TITLE
Integration with Bedtime (clock feature on Android 10)

### ISSUE THREAD

**Issue by Elarcis** [home-assistant/android#1111]
**Is your feature request related to a problem? Please describe.**
I am trying to synchronise my Hass setup with my bedtime. Android 10 has a neat feature called "bedtime", with preferred sleep and waking time. Currently I am tracking the  `next_alarm` sensor but it is neither reliable as a waking alarm (others could get in the way), and I have no sensor for bedtime.

I would like to point out that this is a “native feature” of Android 10 (i.e. a Google app feature), not a 3rd party app.

**Describe the solution you'd like**
It would be neat to have at least three sensor:
* wake time (time)
* sleep time (time)
* whether it is currently bedtime (boolean) — Android actually enables bedtime a bit before the actual sleep time (it's configurable), it might be interesting to either track that as another sensor, or taking it into account with that boolean.

**Describe alternatives you've considered, if any**
I am currently using the `next_alarm` sensor, but as previously explained it is not that reliable.

**Additional context**
![image](https://user-images.githubusercontent.com/990841/97230454-3ab23900-17da-11eb-8944-0218496bfb6d.png)

**Comment by dshokouhi** [comment]
If there is no API for this then we won't be able to get the data from it.  Why do you not find `next_alarm` reliable? did you try to set the allow list on it to make it more reliable?

**Comment by Elarcis** [comment]
It is not reliable because it provides the time of the next alarm, not necessarily next morning. If right now I set an alarm for 23:00, the sensor will adopt this value.

I have no idea whether there's an API for that, I am not an Android dev. I understand that you have limited action if that’s not the case.

**Comment by dshokouhi** [comment]
> It is not reliable because it provides the time of the next alarm

I don't see how that is a reliability issue when that is the exact expectation of the feature it gets the next scheduled alarm

> not necessarily next morning.

As long as this time eventually becomes the next alarm, which it does if it wakes you up, then you will see this update come through.  You just may not see it at the time you want but as long as the app schedules the alarm it will show up when it is the next alarm.

> (others could get in the way),

I see in your original request you said this, if you set the Allow List for the sensor setting then it will only update when the chosen package has an update.

**Comment by HydrelioxGitHub** [comment]
I don't know if I should post in this issue or create another one. Could the alarm sensor get the name of the alarm in his attributes ? In the Clock android stock app, you can label a title. If the sensor can get access to this label then the issue should be resolved as you can filter alarm by name and trigger an automation only for a specific alarm. 

![image](https://user-images.githubusercontent.com/15862735/103773292-1f11ad00-502b-11eb-9857-33fd828c5180.png)

**Comment by dshokouhi** [comment]
> I don't know if I should post in this issue or create another one. Could the alarm sensor get the name of the alarm in his attributes ? In the Clock android stock app, you can label a title. If the sensor can get access to this label then the issue should be resolved as you can filter alarm by name and trigger an automation only for a specific alarm.

Sorry androids API does not give us this data: https://github.com/home-assistant/android/issues/777

Your better off using multiple alarm apps to differentiate them. 


I still don't see how this feature is possible so I am going to close this now unless someone can find API documentation on this.
