### ISSUE TITLE
Status Bar Still Visible in Fullscreen Mode

### ISSUE THREAD

**Issue by mcanning** [home-assistant/android#5539]
**Home Assistant Android app version(s):** 2025.6.6-minimal

**Android version(s):** Android 15 (Lenovo ZUI 17.0.138)

**Device model(s):** Lenovo M11 TB33FU

**Home Assistant version:** 2025.6.3

**Last working Home Assistant release (if known):** Unknown but this post with a different Lenovo model from earlier this year suggests 6+ months https://community.home-assistant.io/t/android-tablet-lenovo-p12-status-bar/827143/3

**Description of problem, include YAML if issue is related to notifications:**
The android status bar is still visible while in fullscreen mode (although missing icons) using the home assistant app on some Lenovo tablets. This behavior is not seen when using hermit browser to create a 'lite app' in fullscreen mode. This is not an issue on my Pixel 8 Pro so it must be related to tablets or the Lenovo ROM. 

**Companion App Logs:** N/A

**Screenshot or video of problem:**
HA App:

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/68fe77f0-b0e8-45c2-9b90-7412f25a454e" />

HA App Settings:

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/20564500-adc2-4c62-bdbc-8083d84757ee" />

Hermit Lite App (with fullscreen mode enabled inside hermit):

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/e92e34af-1cdd-472c-bc01-b446d57d7735" />

**Additional information:**

**Comment by jpelgrom** [comment]
Do you see any difference at all when enabling full screen mode? Is there perhaps a camera/cutout in the screen where there is a black bar?

> Unknown but this post with a different Lenovo model from earlier this year suggests 6+ months https://community.home-assistant.io/t/android-tablet-lenovo-p12-status-bar/827143/3

That message is about Fully Kiosk, an unrelated app. If anything, that suggests this is not an issue for the companion app.

**Comment by mcanning** [comment]
The view with the bar is with fullscreen enabled. When fullscreen is disabled it shows the status bar time/notifications as seen below with fullscreen on and off.

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/fa223627-13d3-40ad-9916-b7a71a55e3d2" />
<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/9c7a6a75-2b42-4597-ae0c-1c1d4ebf1ead" />

> That message is about Fully Kiosk, an unrelated app. If anything, that suggests this is not an issue for the companion app.

I don't think it's related to the kiosk app as the thread suggests. It appears throughout the app.

**Comment by pcicho** [comment]
same problem here, I think it can be related to Lenovo itself, they dropped an update that caused this issue, I've tried to find info on Lenovo-related forums but with no result :(

**Comment by bengtj** [comment]
I have the same issue with both my Lenovo P12 and my new M11 that I planned to use as a dashboard. I believe it was introduced when they added the one vision "full screen window button" where the status bar is. But even if you disable that in the settings it still steals the area from the applications. The setting just removes the three dots:

Posted in this ticket in the lenovo forum:
https://forums.lenovo.com/t5/Lenovo-Android-based-Tablets-and-Phablets/How-to-hide-the-Status-bar-on-a-Tab-P12/m-p/5388426

**Comment by bengtj** [comment]
Youtube and games seems to show full screen as well so there is probably some way to fix this in the home assistant app...

Found some app developer that seems to have a workaround:
https://www.zubersoft.com/mobilesheets/forum/thread-12079.html

It mentions some new "edge-to-edge" layout method and adding a setting to "hide window decor":
https://developer.android.com/develop/ui/views/layout/edge-to-edge

**Comment by RkcCorian** [comment]
Same with me, Lenovo Tab P12. 😢

**Comment by Superpiffer** [comment]
Same problem with a Fire HD 8 with latest version (2025.8.7), either minimal or full app. I had no problem with previous version.

**Comment by ccMatrix** [comment]
Same on Nexus 7 2013. Also worked fine in previous version.

**Comment by danworsley** [comment]
Same for me. I have two Huawei MediaPads (T3 10 AGS) which I have wall mounted in custom made enclosures. These tablets are quite old, they don't have cut outs for the cameras and they are stuck at Android 8.1 stock rom which is EOL. This exact same issue has occurred on both of them, and also occurred on my phone running Android 15. I have rolled back to the previous version of the companion app on both of the tablets and I now have true full screen again. So, for those thinking this might be to do with a rom update, try rolling back first by installing the previous version of the companion app APK like I did.

**Comment by jonicunha** [comment]
Same for me with Lenovo M10 FHD Plus Android 10.

**Comment by ChrisMarriott38** [comment]
We have an Amazon Fire HD10 and there is now a white bar long the bottom permanently. It just appeared with the update. Assuming it's related to this issue? 

This was not showing up before the update on the 15th.

<img width="2048" height="1536" alt="Image" src="https://github.com/user-attachments/assets/42da7741-f2bc-4bd3-b397-60ae3480e67a" />

**Comment by ChrisMarriott38** [comment]
> Same for me. I have two Huawei MediaPads (T3 10 AGS) which I have wall mounted in custom made enclosures. These tablets are quite old, they don't have cut outs for the cameras and they are stuck at Android 8.1 stock rom which is EOL. This exact same issue has occurred on both of them, and also occurred on my phone running Android 15. I have rolled back to the previous version of the companion app on both of the tablets and I now have true full screen again. So, for those thinking this might be to do with a rom update, try rolling back first by installing the previous version of the companion app APK like I did.

Where is the best place to download the version prior to the update on Sept 15th?

**Comment by TimoPtr** [comment]
> > Same for me. I have two Huawei MediaPads (T3 10 AGS) which I have wall mounted in custom made enclosures. These tablets are quite old, they don't have cut outs for the cameras and they are stuck at Android 8.1 stock rom which is EOL. This exact same issue has occurred on both of them, and also occurred on my phone running Android 15. I have rolled back to the previous version of the companion app on both of the tablets and I now have true full screen again. So, for those thinking this might be to do with a rom update, try rolling back first by installing the previous version of the companion app APK like I did.
> 
> Where is the best place to download the version prior to the update on Sept 15th?

Github https://github.com/home-assistant/android/releases

**Comment by ChrisMarriott38** [comment]
> > > Same for me. I have two Huawei MediaPads (T3 10 AGS) which I have wall mounted in custom made enclosures. These tablets are quite old, they don't have cut outs for the cameras and they are stuck at Android 8.1 stock rom which is EOL. This exact same issue has occurred on both of them, and also occurred on my phone running Android 15. I have rolled back to the previous version of the companion app on both of the tablets and I now have true full screen again. So, for those thinking this might be to do with a rom update, try rolling back first by installing the previous version of the companion app APK like I did.
> > 
> > 
> > Where is the best place to download the version prior to the update on Sept 15th?
> 
> Github https://github.com/home-assistant/android/releases

I'm probablly being really dumb but how do i get this as an APK to install? I can see the releases and such but not the packages? 
Thanks so much, as it was downloaded from the Amazon store i think. 

https://github.com/home-assistant/android/tree/2025.8.7

The other tablet I must have installed a fixed APK on a year or more ago because that one is still on a 2024 version, no issues.

**Comment by TimoPtr** [comment]
> > > > Same for me. I have two Huawei MediaPads (T3 10 AGS) which I have wall mounted in custom made enclosures. These tablets are quite old, they don't have cut outs for the cameras and they are stuck at Android 8.1 stock rom which is EOL. This exact same issue has occurred on both of them, and also occurred on my phone running Android 15. I have rolled back to the previous version of the companion app on both of the tablets and I now have true full screen again. So, for those thinking this might be to do with a rom update, try rolling back first by installing the previous version of the companion app APK like I did.
> > > 
> > > 
> > > Where is the best place to download the version prior to the update on Sept 15th?
> > 
> > Github https://github.com/home-assistant/android/releases
> 
> I'm probablly being really dumb but how do i get this as an APK to install? I can see the releases and such but not the packages? 
> Thanks so much, as it was downloaded from the Amazon store i think. 
> 
> https://github.com/home-assistant/android/tree/2025.8.7
> 
> The other tablet I must have installed a fixed APK on a year or more ago because that one is still on a 2024 version, no issues.

Check the artifacts attached to the release there are APKs.

**Comment by habitoti** [comment]
What is the last version that you found working for full screen? Tried some older versions, but at least back to 2025.6.x it still breaks…

**Comment by bengtj** [comment]
I actually believe that this is two separate issues:
1. On newer (Lenovo?) tabs like my new M11 and P12 I believe it is related to the tablet update. Likely related to the new edge-to-edge handling.
2. I went back to using old tablet for my dashboard using an older android version and there I lost full screen when the companion app was updated.

Guessing here, but it could be related to bumping target SDK to 34 and later to 36 which is found in the companion changelog. The source code seems to need updates for fullscreen to continue working:
https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge
https://developer.android.com/about/versions/16/behavior-changes-16

Maybe something like this could be a workaround:
https://stackoverflow.com/questions/79303557/android-api-35-full-screen-app-confusion

**Comment by ChrisMarriott38** [comment]
I luckily had it on multiple devices. I just went back to an older version which has no issues. 

I have this stupid white bar showing up on my Mobile, A fire tablet, and another Tablet since the 9.2 release seemed to be pushed out and it updated. 

I had one tablet that hadn't updated and i noticed it was fine on 2024..4.1-minimal. Fine on a Amazon FireHD10. WIll be applying this downgrade to all devices.

**Comment by nikmedoed** [comment]
**Additional data point: fullscreen safe-area regression (not tablets only).**

* **Device:** Xiaomi Redmi 5 Plus (Android 7.1.2)
* **App versions:** works in **2025.7.1**; broken from **2025.8.7**; still broken in **2025.9.5**
* **Settings:** Full-screen ON, navbar auto-hide enabled in system settings

**Observed**
When the system navigation bar auto-hides, the app still reserves space at the bottom. The WebView is shifted upward, leaving a persistent blank strip. This matches the “white/bottom bar” symptoms others reported, but on an older Xiaomi device — so it’s not limited to Lenovo/ROM updates.

**Expected**
With navbar hidden, no bottom inset should be reserved; WebView should extend to the full physical height.

#### 1) App launch → splash is already cut off by a bottom area reserved for the (hidden) navbar

<details>
<summary>Screenshot</summary>
<img src="https://github.com/user-attachments/assets/f25afc25-b24e-44e0-b243-8125a5eca0e2" width="420">
</details>

#### 2) During loading, layout repositions upward but still keeps that strip

<details>
<summary>Screenshot</summary>
<img src="https://github.com/user-attachments/assets/4ea91b32-b439-4c64-bff5-8a36a5084b42" width="420">
</details>

#### 3) After WebView loads, it inherits the reduced height (blank strip persists at the bottom)

<details>
<summary>Screenshots</summary>
<img src="https://github.com/user-attachments/assets/06987b5d-3522-4dca-8e68-c1a7cabd7d0d" width="420">  
<img src="https://github.com/user-attachments/assets/d14871cc-a970-4566-9cb6-e0c36a27faff" width="420">
</details>

#### Video

<details>
<summary>Proof</summary>

[https://github.com/user-attachments/assets/3792374a-03bc-4b56-be26-14ca7fd28e92](https://github.com/user-attachments/assets/3792374a-03bc-4b56-be26-14ca7fd28e92)

</details>

**Regression notes**

* **2025.7.1:** true fullscreen (no reserved area).
* **From 2025.8.7 onward:** bottom area is wrongly reserved despite navbar being hidden.
* Confirms the issue isn’t Lenovo-specific; reproducible on Android 7.1.2 as well.

<details>
<summary>This is what it looks like if you hide the frontend header</summary>
<img src="https://github.com/user-attachments/assets/4c779b88-00ea-4a7b-b44b-d13bf9b568e2" width="420"> 
</details>

**Comment by skandalfo** [comment]
Exactly the same behavior with versions past 2025.7.1 on Sonoff NSPanelPro running Android 8.1.0: when running full screen with auto-hiding bottom navigation bar, the space for it is left blank. This device has a 480x480 pixel screen, which makes the blank bar very noticeable.

**Comment by brjhaverkamp** [comment]
Just a me-too from my side. Same symptoms as [nikmedoed](https://github.com/nikmedoed) With kiosk_mode hiding the header, and full screen enabled in theapp, I still have a blue bar at the top and a grey bar at the bottom.
This is on an 8 inch lenovo tablet (TB-8505F)
Bert

**Comment by mmarc** [comment]
Same on Google Pixel 7 (Android 6.0.1) and Google Pixel C (Android 8.1.0).
Was working fine with 2025.7.1.

**Comment by Nihvel** [comment]
I recently reset a Huawei Mediapad M5 Lite. This tablet was used as Kiosk for showing one HA dashboard for 3+ years. I had to reset for other reasons, but now that I got HA back installed I noticed a similar issue where the bottom bar showed up from nowhere.

I solved the bottom bar by enabling an option in Android (Emui 8) that allows the navigation panel to hide or show. An arrow down, or gesture up, will toggle the navigation panel. I'm sure there are Launchers that can do the same.
When HA opens, although the navigation panel is hidden, the bottom bar is present. When I slide the finger up it opens the navigation panel on top of this bar, then, after I tap the arrow down and the panel closes, with it also this HA bar closes. 

Issue #2:
Not only the bottom bar, but I also have a top bar too much.

**Comment by ncd7** [comment]
I'm experiencing issues on two devices:
* my phone has the extra blue bar thickness on top
* a tablet has the white bar on the bottom. 
Haven't been able to fix even when playing with the insets vars and setting them to 0px. It really ruins the dashboard space efficiency / look.

**Comment by ncd7** [comment]
I've noticed another tablet has this issue.
Who owns the fix for this, HA core?

**Comment by B1199** [comment]
As a workaround for the problem, I installed https://github.com/KTibow/fullscreen-card. With the button on a dashboard, you can then switch to full screen cleanly.

old LENOVO Tablet with no physical navbar (only "on display" navbar)
HA Companion 2025.10.4 minimal

A other Samsung Tablet with "physical navigation buttons" has no problems with HA Companion Fullscreen Mode.
The kind of Navigation Bar Button seems to play a role.

**Comment by jonicunha** [comment]
> As a workaround for the problem, I installed https://github.com/KTibow/fullscreen-card. With the button on a dashboard, you can then switch to full screen cleanly.
> 
> old LENOVO Tablet with no physical navbar (only "on display" navbar) HA Companion 2025.10.4 minimal
> 
> A other Samsung Tablet with "physical navigation buttons" has no problems with HA Companion Fullscreen Mode. The kind of Navigation Bar Button seems to play a role.

Great! Thank you!

**Comment by jonicunha** [comment]
Using the fullscreen-card and card_mod I was able to make a custom button. Example of a badge:

<img width="1534" height="731" alt="Image" src="https://github.com/user-attachments/assets/c1bb5cdc-b60d-4762-b975-b3ed90f223ff" />

type: custom:fullscreen-card
go_fullscreen: Fullscreen
exit_fullscreen: Exit
card_mod:
  style: |
    ha-card {
      width: 35px !important;    
      height: 37px !important;   
      padding: 0px !important;   
      overflow: hidden; 
      border-radius: 50% !important;
      box-shadow: none;
      background: var(--ha-card-background, rgba(0, 0, 0, 0.3)) !important;
      margin: 0px 0px 0px 0px !important;
      vertical-align: middle; 
      display: inline-flex;
    }
    ha-card > button {
      font-size: 0px !important;
      padding: 0px !important;
      width: 100% !important;      
      height: 100% !important; 
      background: none !important; 
    }
    ha-card > button:before {
      content: "⛶";
      font-family: Arial, sans-serif;
      font-size: 20px !important;
      color: #9e9e9e !important;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100%;
    }

**Comment by sirmeili** [comment]
I get this issue on a Pixel 9 Pro XL with Android 16. It's really annoying. Any chance of a fix?

edit: mainly it's annoying because the color of the bar at the top is not the same as the background color on my dashboard theme,, so it looks really out of place and obvious to have a huge gap at the top of a different color.

**Comment by ncd7** [comment]
> As a workaround for the problem, I installed https://github.com/KTibow/fullscreen-card. With the button on a dashboard, you can then switch to full screen cleanly.
> 
> old LENOVO Tablet with no physical navbar (only "on display" navbar) HA Companion 2025.10.4 minimal
> 
> A other Samsung Tablet with "physical navigation buttons" has no problems with HA Companion Fullscreen Mode. The kind of Navigation Bar Button seems to play a role.

Unfortunately, this doesn't work for me. It only persists on the current screen but if you move back and forth across different pages of the dashboard, it loses the full screen. Interestingly, on my phone it keeps it when I navigate but on two of my tablets it loses the full screen mode as soon as I navigate away from main dashboard page. It's very annoying.

**Comment by Phase-Diagnostics** [comment]
> > As a workaround for the problem, I installed https://github.com/KTibow/fullscreen-card. With the button on a dashboard, you can then switch to full screen cleanly.
> > old LENOVO Tablet with no physical navbar (only "on display" navbar) HA Companion 2025.10.4 minimal
> > A other Samsung Tablet with "physical navigation buttons" has no problems with HA Companion Fullscreen Mode. The kind of Navigation Bar Button seems to play a role.
> 
> Unfortunately, this doesn't work for me. It only persists on the current screen but if you move back and forth across different pages of the dashboard, it loses the full screen. Interestingly, on my phone it keeps it when I navigate but on two of my tablets it loses the full screen mode as soon as I navigate away from main dashboard page. It's very annoying.

Similar with me this doesn't work. From some of my tablets I launch apps like yt music and plex from HA.  The fullscreen-card looks like it changes the ha companion app from full screen to windowed full screen view.  And when I launch an app, the ha companion window minimizes to a small window that is superimposed on top the yt-music app.  It's similar to what happens when you minimize a running video in YouTube.  So instead of a simply screen wipe to get back to HA, now you have to get to that window and maximize it.

**Comment by jonicunha** [comment]
> > > As a workaround for the problem, I installed https://github.com/KTibow/fullscreen-card. With the button on a dashboard, you can then switch to full screen cleanly.
> > > old LENOVO Tablet with no physical navbar (only "on display" navbar) HA Companion 2025.10.4 minimal
> > > A other Samsung Tablet with "physical navigation buttons" has no problems with HA Companion Fullscreen Mode. The kind of Navigation Bar Button seems to play a role.
> > 
> > 
> > Unfortunately, this doesn't work for me. It only persists on the current screen but if you move back and forth across different pages of the dashboard, it loses the full screen. Interestingly, on my phone it keeps it when I navigate but on two of my tablets it loses the full screen mode as soon as I navigate away from main dashboard page. It's very annoying.
> 
> Similar with me this doesn't work. From some of my tablets I launch apps like yt music and plex from HA. The fullscreen-card looks like it changes the ha companion app from full screen to windowed full screen view. And when I launch an app, the ha companion window minimizes to a small window that is superimposed on top the yt-music app. It's similar to what happens when you minimize a running video in YouTube. So instead of a simply screen wipe to get back to HA, now you have to get to that window and maximize it.

I believe you are talking about picture-in-picture. You can disable it for companion app (i did).

**Comment by ncd7** [comment]
Is this issue owed by HA Core or someone else?
It's very visually jarring and while I know the project is open source and they have very limited resources 3 out of 4 dashboards that we heavily use are impacted (and 2 of those doubly impacted as they not only have the extra bar on top but the really ugly white bar on the bottom which also actually cuts off a portion of the dashboard). This is pretty bad and it hasn't even been acknowledged.
What should my expectation be for this actually getting fixed in the next month? Or ever? Do issues like that generally just die on the boards unresolved? If that's the case, I'll have to figure out other options including potentially sideloading the full mode browser thing.

**Comment by ruderthanyou** [comment]
> 
> I believe you are talking about picture-in-picture. You can disable it for companion app (i did).

Yup, that's what I mean. It's exactly what's happening. My long explanation for picture in picture.  I'll try that this evening when I get home.  Thanks for the info.  Didn't even realize there was a setting for that.

**Comment by ruderthanyou** [comment]
> I believe you are talking about picture-in-picture. You can disable it for companion app (i did).

Thanks, that did the trick, well until the companion apps decides to refresh itself, and then you got to force fullscreen mode again.  I can live with that for now.  I bought a few Lenovo tablets on sale late Oct so I might return them so I don't need to deal with this.  Black Friday is coming up; maybe there will be some deals on Samsungs which don't have this issue.

> It's very visually jarring and while I know the project is open source and they have very limited resources 3 out of 4 dashboards that we heavily use are impacted (and 2 of those doubly impacted as they not only have the extra bar on top but the really ugly white bar on the bottom which also actually cuts off a portion of the dashboard). 

I feel your pain. It looks really bad, It should get reported more as Lenovo isn't a minor player in the Android tablet space.  I don't think they can ignore it forever. But will they respond tomorrow, or  6 to 12 months from now?  I don't want to deal with the workaround for long.

**Comment by 404invalid-user** [comment]
getting an issue like others where there's a black bar at the bottom and top of my display when in full screen mode 

fire hd8 5th gen android 5.1.1

**Comment by ncd7** [comment]
Would it make sense to edit the title of the issue a little bit to clarify?

**Comment by TimoPtr** [comment]
> I get this issue on a Pixel 9 Pro XL with Android 16. It's really annoying. Any chance of a fix?
>
> edit: mainly it's annoying because the color of the bar at the top is not the same as the background color on my dashboard theme,, so it looks really out of place and obvious to have a huge gap at the top of a different color.

I think this is another issue. Your issue is you see a white status bar right? Not tight to the fullscreen mode?

If so the issue is a race condition with the frontend where we are trying to get the color of that top bar and we are not getting it on before we actually change the color of the status bar. This should not always be white and sometime it should work.

I'm planning to fix this issue in the coming months but it requires quite significant change of the app so it's going to take time.

**Comment by TimoPtr** [comment]
For the device bellow Android 15 I might be on something, while looking more at the docs to enable edge to edge for Android 16 their is a section about consuming insets https://developer.android.com/develop/ui/views/layout/edge-to-edge#backward-compatible-dispatching and backward compat.

Unfortunately I'm not able to reproduce the issue so I cannot debug properly on my end. So if someone can download the APK from https://github.com/home-assistant/android/pull/6024 (in checks tab -> Pull request at the bottom there is a zip named `artifact` containing all the APK we are building) and see if that solves their issue. If yes I'm going to merge it.

**Comment by B1199** [comment]
> Bei Geräten mit Android-Versionen unter 15 könnte ich Recht haben. Beim genaueren Durchsehen der Dokumentation zur Aktivierung von Edge-to-Edge für Android 16 gibt es einen Abschnitt über das Verwenden von Insets ( https://developer.android.com/develop/ui/views/layout/edge-to-edge#backward-compatible-dispatching ) und Abwärtskompatibilität.
> 
> Leider kann ich das Problem nicht reproduzieren und daher nicht richtig debuggen. Könnte jemand die APK aus [#6024](https://github.com/home-assistant/android/pull/6024) herunterladen (im Reiter „Checks“ → „Pull Request“ befindet sich unten eine ZIP-Datei `artifact`mit allen von uns erstellten APKs) und prüfen, ob das Problem dadurch behoben wird? Falls ja, werde ich den Pull Request mergen.

I tried the "artifact" APK MINIMAL Version, but i got Webpage error net::ERR_UNKNOWN_URL_SCHEME homeassist://auth-callback ... after input Login credentials. (local http://192.168.178.4:8123)
Other Version minimal-2025.10.4 on same tablet device login is OK.

**Comment by TimoPtr** [comment]
> > Bei Geräten mit Android-Versionen unter 15 könnte ich Recht haben. Beim genaueren Durchsehen der Dokumentation zur Aktivierung von Edge-to-Edge für Android 16 gibt es einen Abschnitt über das Verwenden von Insets ( https://developer.android.com/develop/ui/views/layout/edge-to-edge#backward-compatible-dispatching ) und Abwärtskompatibilität.
> > Leider kann ich das Problem nicht reproduzieren und daher nicht richtig debuggen. Könnte jemand die APK aus [#6024](https://github.com/home-assistant/android/pull/6024) herunterladen (im Reiter „Checks“ → „Pull Request“ befindet sich unten eine ZIP-Datei `artifact`mit allen von uns erstellten APKs) und prüfen, ob das Problem dadurch behoben wird? Falls ja, werde ich den Pull Request mergen.
> 
> I tried the "artifact" APK MINIMAL Version, but i got Webpage error net::ERR_UNKNOWN_URL_SCHEME homeassist://auth-callback ... after input Login credentials. (local http://192.168.178.4:8123) Other Version minimal-2025.10.4 on same tablet device login is OK.

I've just tested the APK again and it works properly, can you try again? It's a debug APK so you should have all the logs in logcat if you have ADB

**Comment by ccMatrix** [comment]
I'm kinda stuck at the same point. I can install the apk and run it but I can't login to Home Assistant . It will just show a webview with the ERR_UNKNOWN_URL_SCHEME error. I haven't found a way to bypass that. Feels like an internal intent isn't triggered. Can this happen if both the release app and the debug app are installed on the same system?

**Comment by TimoPtr** [comment]
> I'm kinda stuck at the same point. I can install the apk and run it but I can't login to Home Assistant . It will just show a webview with the ERR_UNKNOWN_URL_SCHEME error. I haven't found a way to bypass that. Feels like an internal intent isn't triggered. Can this happen if both the release app and the debug app are installed on the same system?

No you can install both app in // without any issue. Would you mind sharing some logs? (you can reach out to me on discord if you want)

**Comment by sirmeili** [comment]
> > I get this issue on a Pixel 9 Pro XL with Android 16. It's really annoying. Any chance of a fix?
> > edit: mainly it's annoying because the color of the bar at the top is not the same as the background color on my dashboard theme,, so it looks really out of place and obvious to have a huge gap at the top of a different color.
> 
> I think this is another issue. Your issue is you see a white status bar right? Not tight to the fullscreen mode?
> 
> If so the issue is a race condition with the frontend where we are trying to get the color of that top bar and we are not getting it on before we actually change the color of the status bar. This should not always be white and sometime it should work.
> 
> I'm planning to fix this issue in the coming months but it requires quite significant change of the app so it's going to take time.

No, I have a blueish bar at the top as seen in this screenshot.

![Image](https://github.com/user-attachments/assets/b0f047c6-49f7-4191-b924-0f68f2c97ba7)

**Comment by TimoPtr** [comment]
> > > I get this issue on a Pixel 9 Pro XL with Android 16. It's really annoying. Any chance of a fix?
> > > edit: mainly it's annoying because the color of the bar at the top is not the same as the background color on my dashboard theme,, so it looks really out of place and obvious to have a huge gap at the top of a different color.
> > 
> > 
> > I think this is another issue. Your issue is you see a white status bar right? Not tight to the fullscreen mode?
> > If so the issue is a race condition with the frontend where we are trying to get the color of that top bar and we are not getting it on before we actually change the color of the status bar. This should not always be white and sometime it should work.
> > I'm planning to fix this issue in the coming months but it requires quite significant change of the app so it's going to take time.
> 
> No, I have a blueish bar at the top as seen in this screenshot.
> 
> ![Image](https://github.com/user-attachments/assets/b0f047c6-49f7-4191-b924-0f68f2c97ba7)

Yep sounds like the issue I'm describing. You are in dark mode so it's not white. It's not the same issue as the one describe in this issue which is specific to full screen (from the settings) on old android version. 

You should open another issue with this one.

**Comment by B1199** [comment]
> > > Bei Geräten mit Android-Versionen unter 15 könnte ich Recht haben. Beim genaueren Durchsehen der Dokumentation zur Aktivierung von Edge-to-Edge für Android 16 gibt es einen Abschnitt über das Verwenden von Insets ( https://developer.android.com/develop/ui/views/layout/edge-to-edge#backward-compatible-dispatching ) und Abwärtskompatibilität.
> > > Leider kann ich das Problem nicht reproduzieren und daher nicht richtig debuggen. Könnte jemand die APK aus [#6024](https://github.com/home-assistant/android/pull/6024) herunterladen (im Reiter „Checks“ → „Pull Request“ befindet sich unten eine ZIP-Datei `artifact`mit allen von uns erstellten APKs) und prüfen, ob das Problem dadurch behoben wird? Falls ja, werde ich den Pull Request mergen.
> > 
> > 
> > I tried the "artifact" APK MINIMAL Version, but i got Webpage error net::ERR_UNKNOWN_URL_SCHEME homeassist://auth-callback ... after input Login credentials. (local http://192.168.178.4:8123) Other Version minimal-2025.10.4 on same tablet device login is OK.
> 
> I've just tested the APK again and it works properly, can you try again? It's a debug APK so you should have all the logs in logcat if you have ADB

I tried debugging, but I'm not very good at it. I connected with ADB and ran "adb shell logcat," but there are no messages from the Home Assistant Debug APK in logcat. Please give me some tips on "How to debug ..." Thank you.

**Comment by ccMatrix** [comment]
Once I was past the login issue I can confirm that the full screen bar issue is fixed on my Nexus 7 running Android 6.0.1

**Comment by skandalfo** [comment]
I'm happy to confirm that the minimal debug application from the #6024 PR does indeed fix the fullscreen issue on the Sonoff NSPanel Pro.

**Comment by ncd7** [comment]
> I'm happy to confirm that the minimal debug application from the [#6024](https://github.com/home-assistant/android/pull/6024) PR does indeed fix the fullscreen issue on the Sonoff NSPanel Pro.

Does it address both the top and bottom issues for you?

**Comment by skandalfo** [comment]
> Does it address both the top and bottom issues for you?

I don't think the top bar is shown by default even in non-full-screen mode in my configuration (needs swiping down to show). It might not have been a problem before. Definitely it's not a problem with the test version. The bottom bar that was a problem for sure is fixed now.

**Comment by ruderthanyou** [comment]
I'm unable to get the debug APK to fully launch on my two different Lenovo devices.  An Idea Tab and Idea Tab Pro, both are 2025 models running Android 15.  The issue is if you can get past the initial red Home Assistant logo (it hangs there for some time), and get to the Home Assistant Companion app initial screen, as soon as I click  'Connect to my Home Assistant server' button, the companion app instantly disappears from the screen, basically crashing and dropping you back to the launcher.

On my Samsung S10 FE I get the breathing/spinning logo searching on home network after i click the connect button. And I can login fine.

I can see the logcat, and I see a fail-fast error amoung other items, but i'm a complete novice here.  Let me know what you need as far as log files.

Thanks

**Comment by B1199** [comment]
> Once I was past the login issue I can confirm that the full screen bar issue is fixed on my Nexus 7 running Android 6.0.1

How do you have fix the webview login issue?

**Comment by TimoPtr** [comment]
So thanks to @ccMatrix I've identified the login issue, I'm going to fix it on Wednesday. It's going to take some time to land in the stores since we have some issues with Google these days. 

For everyone testing the debug APK it's not meant to be used as a daily driver. Please don't do it you are going to have many issues like the FailFast that is only enabled on debug that simply crash the app on purpose.

I'm also going to apply the fix for the top and bottom bar this week but it requires a bit more work, than the simple test I did.

**Comment by Nihvel** [comment]
Hi, I still have the issue. Am I the only one? The top and bottom bars are still there. The cache was eptied, the app was also updated. This is the Huawei M5 tablet I mentioned in my previous comment.

![Image](https://github.com/user-attachments/assets/43bf2059-eb43-4e97-8a88-9242fe656bf2)

Somebody mentioned he's having the issue on a Pixel 9 Pro. I've got the same phone, XL version (should not matter), and although there is no extra bottom bar, the top bar seems still present. There is a strange extra bar between the Android status bar and the HA view's title.

![Image](https://github.com/user-attachments/assets/887d3b1b-9095-4bd1-8680-0d9b94919b69)

**Comment by ccMatrix** [comment]
Are you running 2025.11.2 from the releases page? https://github.com/home-assistant/android/releases/tag/2025.11.2
The update from the play store doesn't include the fix yet.

**Comment by Nihvel** [comment]
> Are you running 2025.11.2 from the releases page? https://github.com/home-assistant/android/releases/tag/2025.11.2 The update from the play store doesn't include the fix yet.

No, not from the release page. App: 2025.11.1-full - Core: 2025.11.1 - Supervisor 2025.11.2 - I saw the play store app update today and believed it was the one. 
Seems clear that I'm on the previous version still. If after the real update I notice that it still won't work I'll make sure to report, until then, thanks for the good work!!!

**Comment by ncd7** [comment]
This fixed **ALL** my dashboard issues, _other than_ my Pixel 7 Pro which only exhibits the extra thick blue bar on top. That's probably a separate issue, I'll look for anything existing or create one.
Either way **THANK YOU FOR ADDRESSING THIS!** 
The Dashboards were looking so horrible and this fix now restores them. 
You are the best 🙏🏻

**Comment by mcanning** [comment]
Hi there, I was the original poster. I am unfortunately still seeing the bar on 11.2 on my Lenovo tablet, I have taken a recording to show the behavior.

https://github.com/user-attachments/assets/03754237-5fb3-4fd2-85a6-c9ca7a952b64

Should I reopen this issue?

**Comment by ruderthanyou** [comment]
Hello, I can confirm that on my Lenovo Tab Pros I am still seeing the issue on 11.2.  Same as OP video above.

**Comment by TimoPtr** [comment]
Unfortunately I don't think we can do anything for this at the moment, except waiting for the Frontend to support edge to edge. It seems that the Lenovo Tab Pros is returning a value for the topbar insets, that's why a fake status bar is displayed.

**Comment by ncd7** [comment]
@TimoPtr , is this the same issue as https://github.com/home-assistant/android/issues/6065 ?

**Comment by TimoPtr** [comment]
> [@TimoPtr](https://github.com/TimoPtr) , is this the same issue as [#6065](https://github.com/home-assistant/android/issues/6065) ?

I don't think so

**Comment by ruderthanyou** [comment]
> Unfortunately I don't think we can do anything for this at the moment, except waiting for the Frontend to support edge to edge. It seems that the Lenovo Tab Pros is returning a value for the topbar insets, that's why a fake status bar is displayed.

This looks like it is affecting many Lenovo's running Android 15 (Lenovo ZUI 17.x) or at least the three different models listed in this thread.  I have the Idea Tab (TB336FU) and Idea Tab Pro (TB373FU). And the OP is using a Lenovo Tab M11 (TB330FU) which I believe is Lenovo's most popular tablet at the moment. Also there are a couple posters mentioning that the issue also appears on the Lenovo Tab P12 (which is also the first instance of this being mentioned in https://community.home-assistant.io/t/android-tablet-lenovo-p12-status-bar/827143/3) but not sure what Android version they are running.

Is there anything I can do to provide some debug logs so you can look at this again?

**Comment by mcanning** [comment]
> Unfortunately I don't think we can do anything for this at the moment, except waiting for the Frontend to support edge to edge. It seems that the Lenovo Tab Pros is returning a value for the topbar insets, that's why a fake status bar is displayed.

It sounds like I should recreate this issue over in the Frontend repo then. Do you know if it's already being tracked by chance?

**Comment by mcanning** [comment]
Created https://github.com/home-assistant/frontend/issues/28509 in the frontend repo

**Comment by rob12git** [comment]
I have the same behaviour after updating the Companion-App to versions V12.2 and V12.3. The last working version is V12.1. It is not limited to Lenovo devices. I have a Samsung A52 mobile phone, a Samsung A8 and A9 as wall tablets. An Ipay50 and Lenovo Idea tablet, and they all exhibit the same behaviour. Despite the full-screen setting, the status bar and button bar are displayed. The only workaround is as follows:
1. In the app, go to Settings / Companion App / Screen Orientation ,
 change it to anything, then immediately change it back and close the settings. Full screen will then be displayed until the app is closed. However, after restarting the app, the malfunction reappears.
