### ISSUE TITLE
[NSPanel Pro] App hangs at startup due to blocking network call to www.smatek.com.cn

### ISSUE THREAD

**Issue by Nerzh29** [home-assistant/android#5938]
Home Assistant Android app version(s):
Latest full release from GitHub.

Android version(s):
Stock Android on the device. (Sonoff NSPanel Pro)

Device model(s):
Sonoff NSPanel Pro

Home Assistant version:
Latest (2025.10.2)

Last working Home Assistant release (if known):
N/A, this behavior seems to be consistent across versions.

Description of problem, include YAML if issue is related to notifications:
The Home Assistant Android app on my NSPanel Pro gets stuck on the loading screen at startup and never loads the dashboard.

Through network analysis, I have determined that the app attempts to make a network call to the domain www.smatek.com.cn during its startup sequence. My network firewall blocks this domain by default.

If the domain is blocked, the app hangs indefinitely on the loading screen.

If I temporarily allow the domain, the app starts up immediately and loads the dashboard correctly.

My Home Assistant installation is 100% local, using only Zigbee devices. I do not have the Tuya integration or any other cloud-based integration installed that would justify this external call. The issue appears to be with the client app itself.

This raises two critical questions:

Why is the Android client app making a hardcoded call to a Tuya-related manufacturer domain (smatek.com.cn) at startup?

Why does this network call completely block the UI from rendering instead of timing out or failing gracefully in the background? This makes the app unusable on networks with strict egress filtering.

Companion App Logs:
(Note: It's difficult to extract detailed logs from the NSPanel. I will try to get them if possible. The core issue is reproducible by simply blocking the www.smatek.com.cn domain.)

(Collez les logs ici si vous arrivez à les obtenir)
Screenshot or video of problem:
(I can provide a photo of the NSPanel stuck on the "Loading data" screen if necessary.)

Additional information:
This issue forces me to allow a suspicious external domain for the app to function, which defeats the purpose of having a fully local smart home setup. The app should be able to function without arbitrary external cloud dependencies.

**Comment by jpelgrom** [comment]
The app is not using this URL, nor is it hardcoded somewhere. You can search in the source code yourself and see it doesn't appear anywhere: https://github.com/search?q=repo%3Ahome-assistant%2Fandroid+smatek&type=code

Have you tested on another device? My guess would be that your device somehow has this as a requirement.

**Comment by TimoPtr** [comment]
If I remember right the sonoff nspanel is in the end a tuya t6e. That explains this URL. I suppose that they are doing some analytics on the apps used on the device.

Can you check if there are any settings to disable the analytics?

Based on this I'm going to close the issue since like @jpelgrom the app itself never makes any call to any third party.

**Comment by jpelgrom** [comment]
> the app itself never makes **any** call to **any** third party

(emphasis added)

That's not what I said and not true, especially if using the full version. The app integrates with push infrastructure hosted by the Open Home Foundation, Firebase Cloud Messaging, and Sentry. But blocking access to the related domains should only block that app feature from working and not the entire app (we frequently do this during dev when not registered).

**Comment by TimoPtr** [comment]
> > the app itself never makes **any** call to **any** third party
> 
> (emphasis added)
> 
> That's not what I said and not true, especially if using the full version. The app integrates with push infrastructure hosted by the Open Home Foundation, Firebase Cloud Messaging, and Sentry. But blocking access to the related domains should only block that app feature from working and not the entire app (we frequently do this during dev when not registered).

I'm assuming it's the minimal version on these devices. They don't have the play store.

**Comment by Nerzh29** [comment]
Thank you for the detailed explanation.
I understand that the smatek.com.cn URL is not being called by the Home Assistant Companion App itself, but likely by the underlying firmware of the Sonoff NSPanel Pro.
However, it is very strange that this external network call completely prevents the app from starting up. It seems like the app's startup process is being blocked until this call either succeeds or fails, which leads to an indefinite freeze when a firewall blocks the domain.
This behavior makes the app unusable on secured networks without creating a specific exception for this unexpected domain.

**Comment by jpelgrom** [comment]
> I'm assuming it's the minimal version on these devices. They don't have the play store.

You can use that, and that's also suggested, but the issue description says that the full version was used. Also good to have the context in case someone links to the comment in another discussion in the future.

**Comment by TimoPtr** [comment]
> Thank you for the detailed explanation.
> I understand that the smatek.com.cn URL is not being called by the Home Assistant Companion App itself, but likely by the underlying firmware of the Sonoff NSPanel Pro.
> However, it is very strange that this external network call completely prevents the app from starting up. It seems like the app's startup process is being blocked until this call either succeeds or fails, which leads to an indefinite freeze when a firewall blocks the domain.
> This behavior makes the app unusable on secured networks without creating a specific exception for this unexpected domain.

That's something that the manufacturer is doing at the OS level unfortunately completely out of the app control.

**Comment by thib3113** [comment]
Hi @Nerzh29 how do you debug this exactly ? 

In fact, I have a similar bug (the app gets stuck on the loading screen at startup and never loads the dashboard) . But, it's not linked to this network call ... If I disable my firewall, I can curl the domain, and home assistant doesn't works too ... 

BUT ! I figure that the my problem starts with version 2025.8.3 ( no problem with 2025.8.1 ) . Same for you ? or it's a totally different bug ? ( also, I'm using minimal version )

**Comment by Nerzh29** [comment]
Hi @thib3113,

I am also using the minimal version.

Unfortunately, I can't confirm if version 2025.8.3 is the specific cause, because I implemented my network protections right around the same time. I haven't had a chance to test it with any previous versions.

In any case, the symptom is identical: the NSPanel (Home Assistant) gets stuck in a loading loop on startup.

For now, the only solution I've found is to allow the screen to communicate externally. If I let it access the outside network, it works fine.

**Comment by thib3113** [comment]
Hum, 

FYI, It seems that I fixed my problem on one of my nspanel pro . I'm trying on other one . 

My fix was to update the firmware ( V3.4.1 => 3.7.1 ), and it seems to update the webview . 

My nspanel pro doesn't have access to internet (so, not to the domain concerned) . But, also I removed all unused all apps like written [here](https://blakadder.com/nspanel-pro-secrets/#debloat-apps) .


It seems that my nspanel try to access to this domain, but, it doesn't seems to cause problems : 
```
11-02 22:15:01.367   499 19736 D NetworkMonitor/NetworkAgentInfo [WIFI () - 100]: PROBE_DNS www.smatek.com.cn 801ms OK 211.149.229.123
11-02 22:15:01.368   499 19737 D NetworkMonitor/NetworkAgentInfo [WIFI () - 100]: PROBE_DNS www.smatek.com.cn 802ms OK 211.149.229.123
11-02 22:15:01.432   499 19737 D NetworkMonitor/NetworkAgentInfo [WIFI () - 100]: PROBE_HTTP http://www.smatek.com.cn/generate_204.html Probe failed with exception java.net.ConnectException: Failed to connect to www.smatek.com.cn/211.149.229.123:80
11-02 22:15:01.437   499 19736 D NetworkMonitor/NetworkAgentInfo [WIFI () - 100]: PROBE_HTTPS http://www.smatek.com.cn/generate_204.html Probe failed with exception java.net.ConnectException: Failed to connect to www.smatek.com.cn/211.149.229.123:80
```

**Comment by Nerzh29** [comment]
I am going to try the firmware update. Could you tell me what procedure you used to do it? I hope this will solve my problem too.

**Comment by thib3113** [comment]
@Nerzh29 I use this app : https://github.com/seaky/nspanel_pro_roottool_apk/releases 

And you can search updates depending on your current version ( you can get it with `adb shell getprop ro.build.display.id` ) . 

you can get links to OTA here : https://github.com/seaky/nspanel_pro_roottool_apk?tab=readme-ov-file#usage . 

If you version is recent, maybe you can check in the issue : https://github.com/seaky/nspanel_pro_roottool_apk/issues/1#issuecomment-2358450356 

If you have version 3.5 or higher https://github.com/seaky/nspanel_pro_roottool_apk/issues/1#issuecomment-2600222720 

( in fact, lot of OTA urls are available in the comments of this issue . Just, after 3.5.0, OTA are just diff between two versions, so you need to get the correct diff )

---

It seems that you can update your webview in other ways ... but all my tests failed, so I prefer to directly update the firmware

**Comment by Nerzh29** [comment]
Thanks for the info. I'll check which version I have, but I believe I'm on 3.5.0. I'll run the update and will let you know if that solves the issue.

**Comment by Nerzh29** [comment]
Hi @thib3113,

I wanted to let you know that I've upgraded the firmware to 4.0.7.

Unfortunately, I'm still experiencing the same boot stall issue with Home Assistant, even after disabling every possible application I could.

Thanks a lot for your help anyway, I really appreciate it. Hopefully, I'll manage to find the solution someday.
